---
- name: Apply common configuration to the whole fleet
  hosts: all
  become: true
  tags: [common]
  roles:
    - common

- name: Apply node_exporter to the whole fleet
  hosts: all
  become: true
  tags: [node_exporter]
  roles:
    - node_exporter

- name: Apply the host health check to the whole fleet
  hosts: all
  become: true
  tags: [healthcheck]
  roles:
    - healthcheck

- name: Apply Prometheus server configuration
  hosts: observability
  become: true
  tags: [prometheus]
  roles:
    - prometheus

- name: Apply Grafana configuration
  hosts: observability
  become: true
  tags: [grafana]
  roles:
    - grafana

- name: Apply Alertmanager configuration
  hosts: observability
  become: true
  tags: [alertmanager]
  roles:
    - alertmanager

- name: Apply GitLab-specific configuration
  hosts: gitlab.beamline
  become: true
  tags: [gitlab]
  roles:
    - gitlab

- name: Apply HPC/SLURM-specific configuration
  hosts: hpc
  become: true
  tags: [slurm]
  roles:
    - slurm

- name: Apply Tango Database configuration
  hosts: tango_db
  become: true
  tags: [tango_db]
  roles:
    - tango_db

- name: Apply Tango device-server configuration
  hosts: tango_ds
  become: true
  tags: [tango_ds]
  roles:
    - tango_ds

- name: Apply package-host configuration
  hosts: pkg.beamline
  become: true
  tags: [pkg]
  roles:
    - pkg

- name: Apply Kubernetes node configuration
  hosts: kubernetes
  become: true
  tags: [k8s]
  roles:
    - k8s
