[control]
admin.beamline      ansible_host=10.10.10.11

[gitlab]
gitlab.beamline     ansible_host=10.10.10.12

[packaging]
pkg.beamline        ansible_host=10.10.10.13

[configmgmt]
puppet.beamline     ansible_host=10.10.10.14

[k8s_control]
k8cp.beamline       ansible_host=10.10.10.21

[k8s_workers]
k8w1.beamline       ansible_host=10.10.10.22
k8w2.beamline       ansible_host=10.10.10.23

[kubernetes:children]
k8s_control
k8s_workers

[tango]
tango-db.beamline   ansible_host=10.10.10.31
tango-ds.beamline   ansible_host=10.10.10.32

[observability]
obs.beamline        ansible_host=10.10.10.41
